# Generated by Django 5.2.6 on 2025-10-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification'),
        ('hospitals', '0002_alter_hospital_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_hospital', 'Can manage hospital data'), ('can_view_all_hospitals', 'Can view all hospitals'), ('can_manage_donors', 'Can manage donor data'), ('can_view_all_requests', 'Can view all blood requests')]},
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.OneToOneField(blank=True, help_text='Hospital associated with this user (for hospital staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_user', to='hospitals.hospital'),
        ),
    ]
