# Generated by Django 5.2.6 on 2025-10-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_hospital'),
        ('hospitals', '0002_alter_hospital_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital associated with this user (for hospital staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='hospitals.hospital'),
        ),
    ]
