# Generated by Django 5.2.6 on 2025-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
    ]
