# Generated by Django 5.2.6 on 2025-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
