# Generated by Django 5.2.7 on 2025-10-29 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donor_available_from'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='available_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_type', 'is_available', 'available_from'], name='donor_matching_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_available', 'available_from'], name='donor_available_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_type', 'last_donation_date'], name='donor_donation_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['last_donation_date', 'is_available'], name='donor_recent_donation_idx'),
        ),
    ]
