# Generated by Django 5.2.6 on 2025-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorresponse',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
