# Generated by Django 5.2.7 on 2025-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_donorresponse_fulfilled'),
        ('donors', '0002_alter_donor_available_from'),
        ('hospitals', '0002_alter_hospital_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorresponse',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='donorresponse',
            name='fulfilled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', 'blood_type', '-created_at'], name='blood_req_matching_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['hospital', 'status', '-created_at'], name='blood_req_hospital_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', '-created_at'], name='blood_req_open_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_type', 'status'], name='blood_req_analytics_idx'),
        ),
        migrations.AddIndex(
            model_name='donorresponse',
            index=models.Index(fields=['fulfilled', 'accepted_at'], name='donor_resp_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='donorresponse',
            index=models.Index(fields=['donor', '-accepted_at'], name='donor_resp_history_idx'),
        ),
        migrations.AddIndex(
            model_name='donorresponse',
            index=models.Index(fields=['request', 'fulfilled'], name='donor_resp_fulfill_idx'),
        ),
    ]
