# Generated by Django 5.2.7 on 2025-10-29 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospital_user'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_verified', 'primary_location', 'name'], name='hospital_directory_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_verified', '-created_at'], name='hospital_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['primary_location', 'is_verified'], name='hospital_location_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name', 'is_verified'], name='hospital_name_idx'),
        ),
    ]
